### PR TITLE
feat(DS-367): add compatibility with Open edX olive release

### PR DESCRIPTION
**Pull request by JuanDavidBuitrago**
## Description

This PR adds support for the Open edx olive release. Adds issue and PR templates.

## Testing instructions

1. Create an environment with Olive release, you can use [Tutor](https://docs.tutor.overhang.io/index.html) or [TVM](https://github.com/eduNEXT/tvm)
2. Install the Django plugin eox-hooks, you can use steps in [Tutor documentation](https://docs.tutor.overhang.io/configuration.html#installing-extra-xblocks-and-requirements).
3. Run [test cases](https://docs.google.com/document/d/1f7LkXyxUbBcAdkDsWhtEzNfVNFFmV65enpKrEUUnirw/edit?usp=sharing) 

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

### CODE REVIEW

**Comment by mariajgrimaldi** [comment]
I tested this in my local environment with the following results:
Registration, certificates, login, OK
Now, after the enrollment I'm receiving an empty form:
image
There's an issue with the configuration in the document, fields change according the event received. For example, if the event is enrollment, the object received will be enrollment data, not a user, as assumed in the configurations. So, the correct configuration would be:
```
    "post_enrollment": {
        "action": "post_to_webhook_url",
        "config":{
            "fields": {
                "recipient_email": "enrollment.user.pii.email",
            },
            "send_enrollment_data": True,
            "url":"https://webhook.site/webhook-id/"
        },
        "fail_silently": True,
        "module": "eox_hooks.actions"
    }
```
Hence, the document needs to be updated.

**Review by mariajgrimaldi — CHANGES_REQUESTED** [review]
I tested this in my local environment with the following results:
Registration, certificates, login, OK
Now, after the enrollment I'm receiving an empty form:
image
There's an issue with the configuration in the document, fields change according the event received. For example, if the event is enrollment, the object received will be enrollment data, not a user, as assumed in the configurations. So, the correct configuration would be:
```
    "post_enrollment": {
        "action": "post_to_webhook_url",
        "config":{
            "fields": {
                "recipient_email": "enrollment.user.pii.email",
            },
            "send_enrollment_data": True,
            "url":"https://webhook.site/webhook-id/"
        },
        "fail_silently": True,
        "module": "eox_hooks.actions"
    }
```
Hence, the document needs to be updated.

**Comment by MaferMazu** [comment]
I think removing the backends we don't use is a good idea. If it's a lot for this PR, maybe you can open another PR with that. What do you think?

**Review by mariajgrimaldi — APPROVED** [review]

**Comment by JuanDavidBuitrago** [comment]
> I think removing the backends we don't use is a good idea. If it's a lot for this PR, maybe you can open another PR with that. What do you think?

I think we can maintain this actual backends at less for one more release, this plugin not change too much. We have Lilac backends to support Nutmeg and Olive. Let me know if you have other recommendation.

**Review by MaferMazu — APPROVED** [review]
I was referring to these backends that we are no longer using, even in lilac:
[course_modes_j_v1.py](https://github.com/eduNEXT/eox-hooks/blob/master/eox_hooks/edxapp_wrapper/backends/course_modes_j_v1.py)
[courses_j_v1.py](https://github.com/eduNEXT/eox-hooks/blob/master/eox_hooks/edxapp_wrapper/backends/courses_j_v1.py)
[enrollments_j_v1.py](https://github.com/eduNEXT/eox-hooks/blob/master/eox_hooks/edxapp_wrapper/backends/enrollments_j_v1.py)
[models_j_v1.py](https://github.com/eduNEXT/eox-hooks/blob/master/eox_hooks/edxapp_wrapper/backends/models_j_v1.py)

But I don't think that improvement should stop this PR; we can do it later.

**Pull request merged**
